In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [1]:
print ("Hello, World!")

Hello, World!


In [4]:

documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [30]:
token= [sentence.lower().split() for sentence in documents]
print(token)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]


In [42]:
words_all = [[word] for sentence in token for word in sentence]
print (words_all)

[['people'], ['watch'], ['movie'], ['people'], ['watch'], ['cricket'], ['people'], ['like'], ['movie'], ['people'], ['like'], ['cricket']]


In [41]:
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(words_all)
print (encoder.categories_[0])

['cricket' 'like' 'movie' 'people' 'watch']


In [43]:
print (token)
for sentence in token:
    print (sentence)

[['people', 'watch', 'movie'], ['people', 'watch', 'cricket'], ['people', 'like', 'movie'], ['people', 'like', 'cricket']]
['people', 'watch', 'movie']
['people', 'watch', 'cricket']
['people', 'like', 'movie']
['people', 'like', 'cricket']


In [49]:
print (encoder.categories_[0])
for sentence in token:
    en_sen = encoder.transform([[word] for word in sentence])
    print ("\nsentence:", sentence)
    print (en_sen)

['cricket' 'like' 'movie' 'people' 'watch']

sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [50]:
from sklearn.feature_extraction.text import CountVectorizer


In [51]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]


In [52]:
bow = CountVectorizer()

In [56]:
bow_mat = bow.fit_transform(documents)
print (bow_mat.toarray())
print (bow.get_feature_names_out())
print (bow_mat.toarray().shape)
print (bow_mat.toarray()[0])

[[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]
['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
(4, 8)
[1 1 0 0 0 2 1 2]


In [60]:
DOC1= ["RAMESH KUMAR IS A GOOD BOY, WORK IN MALAYSIA AND HE IS A SOFTWARE ENGINEER, HE HAVE TWO SONS, HIS WIFE NAME IS SUREKHA AND SHE IS A HOUSE WIFE, RAMESH KUMAR LIKE TO PLAY CRICKET AND FOOTBALL, HE ALSO LIKE TO WATCH MOVIES AND TV SHOWS, HE IS A VERY GOOD COOK, HIS FAVORITE DISH IS BIRYANI, HE ALSO LIKE TO TRAVEL AND EXPLORE NEW PLACES, HE HAVE A LOT OF FRIENDS AND HE IS VERY SOCIAL PERSON, RAMESH KUMAR IS A VERY HARDWORKING PERSON AND HE ALWAYS STRIVE FOR SUCCESS, HE BELIEVE IN WORK HARD PLAY HARD, HE ALSO BELIEVE IN LIVING LIFE TO THE FULLEST, RAMESH KUMAR IS A VERY POSITIVE PERSON AND HE ALWAYS LOOK ON THE BRIGHT SIDE OF LIFE, HE IS A VERY KIND AND GENEROUS PERSON AND HE ALWAYS HELP OTHERS IN NEED, RAMESH KUMAR IS A VERY LOVING HUSBAND AND FATHER AND HE ALWAYS PUT HIS FAMILY FIRST"]
bow1 = CountVectorizer()
bow_mat1 = bow1.fit_transform(DOC1)
print (bow_mat1.toarray())      
print (bow1.get_feature_names_out())
print (bow_mat1.toarray().shape)

[[ 3  4 12  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  1
   2 14  1  3  1  1  4 11  1  5  2  3  1  1  1  1  1  1  1  1  1  2  1  1
   4  1  2  1  1  5  1  1  1  1  1  1  1  1  1  2  4  1  1  1  6  1  2  2]]
['also' 'always' 'and' 'believe' 'biryani' 'boy' 'bright' 'cook' 'cricket'
 'dish' 'engineer' 'explore' 'family' 'father' 'favorite' 'first'
 'football' 'for' 'friends' 'fullest' 'generous' 'good' 'hard'
 'hardworking' 'have' 'he' 'help' 'his' 'house' 'husband' 'in' 'is' 'kind'
 'kumar' 'life' 'like' 'living' 'look' 'lot' 'loving' 'malaysia' 'movies'
 'name' 'need' 'new' 'of' 'on' 'others' 'person' 'places' 'play'
 'positive' 'put' 'ramesh' 'she' 'shows' 'side' 'social' 'software' 'sons'
 'strive' 'success' 'surekha' 'the' 'to' 'travel' 'tv' 'two' 'very'
 'watch' 'wife' 'work']
(1, 72)
