In [87]:
import numpy as np
arr=np.array([1,2,3,4,5,2,3,4,5])
print(arr)
np.unique(arr);
print (arr)
arr.shape
arr.reshape(3,3)

list=[1,2,3,4,5,6,7,8,9]
arr=np.array(list)
print(arr)
arr.shape
arr[0]

[1 2 3 4 5 2 3 4 5]
[1 2 3 4 5 2 3 4 5]
[1 2 3 4 5 6 7 8 9]


1

In [98]:
arr[5:]=2
print(arr)
arr1=arr.copy();
arr1[5:]=0
print(arr1)
print(arr)

[1 6 6 6 6 2 2 2 2]
[1 6 6 6 6 0 0 0 0]
[1 6 6 6 6 2 2 2 2]
